services:
  frontend:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.dev.frontend
    image: hoseok-frontend:latest
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"