FROM python:3.11
RUN pip install poetry
WORKDIR /app
COPY crawler/pyproject.toml crawler/poetry.lock ./
RUN poetry install --no-root
CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]