FROM python:3.11
RUN pip install poetry
WORKDIR /app
COPY backend/pyproject.toml backend/poetry.lock ./
RUN poetry install --no-root
CMD ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]